name: numerical_ops
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - anyio=4.10.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.0=py311haa95532_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.17.0=py311haa95532_0
  - beautifulsoup4=4.14.2=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py311haa95532_0
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.1.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - contourpy=1.3.3=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h885b0b7_1
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py311haa95532_1
  - harfbuzz=10.2.0=he2f9f60_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py311haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py311h4442805_0
  - ipython=9.7.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - ipywidgets=8.1.7=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.12.1=py311haa95532_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter=1.1.1=py311haa95532_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_1
  - jupyter_console=6.6.3=py311haa95532_0
  - jupyter_core=5.9.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jupyter_server=2.16.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - jupyterlab=4.5.0=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_0
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - kiwisolver=1.4.9=py311h03f52e7_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxgboost=1.7.6=cpu_h0f92c63_6
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - llvmlite=0.45.1=py311h4f568be_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.6=py311haa95532_1
  - matplotlib-base=3.10.6=py311h43afe63_1
  - matplotlib-inline=0.2.1=py311haa95532_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - nbclient=0.10.2=py311haa95532_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - notebook=7.5.0=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - numba=0.62.1=py311h5e69a0e_1
  - numexpr=2.14.1=py311h7660c64_0
  - numpy=2.3.5=py311h050da96_0
  - numpy-base=2.3.5=py311h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=py311haa95532_1
  - pandas=2.3.3=py311h42c1672_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=py311haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py311haa95532_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pure_eval=0.2.3=py311haa95532_0
  - py-xgboost=1.7.6=cpu_py311h997e2c4_6
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pyparsing=3.2.5=py311haa95532_0
  - pyqt=6.9.1=py311h12ec796_0
  - pyqt6-sip=13.10.2=py311h630b2a1_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-json-logger=4.0.0=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311h7149c55_1
  - qtbase=6.9.2=h06bae2a_5
  - qtconsole=5.7.0=py311haa95532_0
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtpy=2.4.3=py311haa95532_0
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.28.0=py311h114bc41_0
  - scikit-learn=1.7.1=py311h3fbe716_0
  - scipy=1.16.3=py311hbd6d557_0
  - seaborn=0.13.2=py311haa95532_3
  - send2trash=1.8.2=py311haa95532_1
  - setuptools=80.9.0=py311haa95532_0
  - shap=0.48.0=cpu_py311h01c55c6_1
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=py311haa95532_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - sniffio=1.3.1=py311haa95532_0
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - terminado=0.18.1=py311haa95532_0
  - threadpoolctl=3.5.0=py311h4442805_1
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - widgetsnbextension=4.0.14=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xgboost=1.7.6=cpu_py311h997e2c4_6
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\digit\miniconda3\envs\numerical_ops
